name: Github Releases To Discord
author: SethCohen
description: Automatically send a stylized Discord webhook of a GitHub Release description to a specified Discord channel.
inputs:
  webhook_url:
    description: Discord's webhook url. Use GH repo secrets.
    required: true
  color:
    description: Decimal color value for embed.
    required: false
    default: '2105893'
  username:
    description: String username for webhook.
    required: false
  avatar_url:
    description: String url to webhook avatar picture.
    required: false
  content:
    description: String content for webhook.
    required: false
  footer_title:
    description: Title for the footer.
    required: false
  footer_icon_url:
    description: Icon url for the footer.
    required: false
  footer_timestamp:
    description: Timestamp for the footer.
    required: false
  max_description:
    description: Max length for the description.
    required: false
    default: '4096'
  reduce_headings:
    description: Converts H3 to bold, h2 to bold & underline.
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: file-text
  color: blue