name: Github Releases To Discord
author: SethCohen
description: Send automatic styled releases to Discord.
inputs:
  webhook_url:
    description: Discord's webhook url. Use GH repo secrets.
    required: true
  colour:
    description: Decimal colour value for embed.
    required: false
    default: '2105893'
  username:
    description: String username for webhook.
    required: false
    default: 'Release Changelog'
  avatar_url:
    description: String url to webhook avatar picture.
    required: false
    default: 'https://cdn.discordapp.com/avatars/487431320314576937/bd64361e4ba6313d561d54e78c9e7171.png'
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: file-text
  color: gray-dark