name: Update SemVer Tags
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  update_semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update semver tags
        uses: haya14busa/action-update-semver@v1